[package]
name = "dmntk-test-runner"
version = "0.3.3"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
description = "DMNTK | Test runner"
documentation = "https://docs.rs/dmntk-test-runner"
repository = "https://github.com/dmntk-io/dmntk.test.runner.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
base64 = "0.21.2"
http = "0.2.9"
regex = "1.9.1"
reqwest = { version = "0.11.18", default-features = false, features = ["blocking", "json", "rustls-tls"] }
roxmltree = "0.18.0"
serde = { version = "1.0.178", features=["derive"] }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
url = "2.4.0"
