test_cases_dir_path: ../tck/TestCases
file_search_pattern: compliance-level-3/0016
evaluate_url: http://127.0.0.1:22022/tck
report_file: output/results_debug.csv
tck_report_file: output/tck_results_debug.csv
stop_on_failure: false